import type { SheetConfig, CharLayout } from './heroSprites';

export type EnemyKey = 'enemy' | 'scorpion' | 'bear' | 'reaper';

export const ENEMY_SHEET_CONFIGS: Record<EnemyKey, SheetConfig> = {
  enemy: {
    name: 'enemy',
    url: '/assets/gen/enemy/enemy_goblin.png',
    frameW: 32,
    frameH: 32,
    enabled: true,
    colorKey: null,
    singleFrame: true,
    walkUrl: '/assets/gen/enemy/goblin-walk.png',
    walkFrameW: 32,
    walkFrameH: 32,
    walkFrames: 4,
    battleUrl: '/assets/gen/enemy/goblin-battle.png',
    battleFrameW: 512,
    battleFrameH: 512,
    castBattleUrl: '/assets/gen/enemy/goblin-cast-battle.png',
    castBattleFrameW: 512,
    castBattleFrameH: 512,
    hurtBattleUrl: '/assets/gen/enemy/goblin-hurt-battle.png',
    hurtBattleFrameW: 512,
    hurtBattleFrameH: 512,
  },
  scorpion: {
    name: 'scorpion',
    url: '/assets/gen/enemy/enemy_scorpion.png',
    frameW: 32,
    frameH: 32,
    enabled: true,
    colorKey: null,
    singleFrame: true,
    walkUrl: '/assets/gen/enemy/scorpion-walk.png',
    walkFrameW: 32,
    walkFrameH: 32,
    walkFrames: 4,
    battleUrl: '/assets/gen/enemy/scorpion-battle.png',
    battleFrameW: 512,
    battleFrameH: 512,
    castBattleUrl: '/assets/gen/enemy/scorpion-cast-battle.png',
    castBattleFrameW: 512,
    castBattleFrameH: 512,
    hurtBattleUrl: '/assets/gen/enemy/scorpion-hurt-battle.png',
    hurtBattleFrameW: 512,
    hurtBattleFrameH: 512,
  },
  bear: {
    name: 'bear',
    url: '/assets/gen/enemy/enemy_bear.png',
    frameW: 32,
    frameH: 32,
    enabled: true,
    colorKey: null,
    singleFrame: true,
    walkUrl: '/assets/gen/enemy/bear-walk.png',
    walkFrameW: 32,
    walkFrameH: 32,
    walkFrames: 4,
    battleUrl: '/assets/gen/enemy/bear-battle.png',
    battleFrameW: 512,
    battleFrameH: 512,
    hurtBattleUrl: '/assets/gen/enemy/bear-hurt-battle.png',
    hurtBattleFrameW: 512,
    hurtBattleFrameH: 512,
  },
  reaper: {
    name: 'reaper',
    url: '/assets/gen/enemy/enemy_reaper.png',
    frameW: 32,
    frameH: 32,
    enabled: true,
    colorKey: null,
    singleFrame: true,
    walkUrl: '/assets/gen/enemy/reaper-walk.png',
    walkFrameW: 32,
    walkFrameH: 32,
    walkFrames: 4,
    battleUrl: '/assets/gen/enemy/reaper-battle.png',
    battleFrameW: 512,
    battleFrameH: 512,
    hurtBattleUrl: '/assets/gen/enemy/reaper-hurt-battle.png',
    hurtBattleFrameW: 512,
    hurtBattleFrameH: 512,
  },
};

export const ENEMY_LAYOUTS: Record<EnemyKey, CharLayout> = {
  enemy: { sheet: 'enemy', col: 0, row: 39, walkFrames: 6, dirRow: [0, 1, 2, 3] },
  scorpion: { sheet: 'scorpion', col: 0, row: 39, walkFrames: 6, dirRow: [0, 1, 2, 3] },
  bear: { sheet: 'bear', col: 0, row: 39, walkFrames: 6, dirRow: [0, 1, 2, 3] },
  reaper: { sheet: 'reaper', col: 0, row: 39, walkFrames: 6, dirRow: [0, 1, 2, 3] },
};

export const ZONE_ENEMY_KEY: Record<number, EnemyKey> = {
  1: 'enemy',
  2: 'scorpion',
  3: 'bear',
  4: 'reaper',
};

export const ENEMY_SHEET_CONFIG = ENEMY_SHEET_CONFIGS.enemy;
export const ENEMY_LAYOUT = ENEMY_LAYOUTS.enemy;